# Generated by Django 2.2.5 on 2020-05-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='cname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
