# Generated by Django 2.2.5 on 2020-05-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CollectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('wastetype', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
