# Generated by Django 2.2.5 on 2020-05-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_bookform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookform',
            old_name='user',
            new_name='username',
        ),
    ]
