# Generated by Django 2.2.5 on 2020-05-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_payment_sellpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sellpayment',
            name='cardnumber',
            field=models.IntegerField(),
        ),
    ]
